docker_image_tag: 695e33b9bd3d33e96442ed6a27bb5828f54fd53d
mcrt_domain: genegraph-gene-validity.stage.clingen.app
static_ip_name: global-stage-genegraph-gene-validity-ip
dev_static_ip_name: global-stage-dev-genegraph-gene-validity-ip
dev_mcrt_domain: genegraph-gene-validity-dev.stage.clingen.app
docker_image_location: "us-east1-docker.pkg.dev/clingen-stage/genegraph-stage/genegraph-gene-validity"
platform: stage
graphql_endpoint_replicas: 1
